### ISSUE TITLE
`GrafanaOpenTelemetryResourceDetector.Detect` throw when built with -p:PublishSingleFile=true

### ISSUE THREAD

**Issue by chinwobble** [grafana/grafana-opentelemetry-dotnet#65]
# Bug Report
`GrafanaOpenTelemetryResourceDetector.Detect` throw when built in self contained mode.

## Environment Details:
Package version
```xml
<PackageReference Include="Grafana.OpenTelemetry" Version="0.6.0-beta.2" />
```
Package is with the following flags
dotnet version 7.0.101
```
dotnet publish -r win-x64 --self-contained true -p:PublishSingleFile=true
```
* 

## Symptom

**What is the expected behavior?**

This package should not cause the app to crash if built in self contained mode.

**What is the actual behavior?**

The app is unable to startup when running in self-contained mode.

What did you see instead?

throws the following exception.
```
System.ArgumentException: The path is empty. (Parameter 'path')
   at System.IO.Path.GetFullPath(String path)
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at Grafana.OpenTelemetry.GrafanaOpenTelemetryResourceDetector.Detect()
   at OpenTelemetry.Resources.ResourceBuilder.Build()
   at OpenTelemetry.Metrics.MeterProviderSdk..ctor(IServiceProvider serviceProvider, Boolean ownsServiceProvider)
   at OpenTelemetry.Metrics.MeterProviderBuilderBase.<>c.<.ctor>b__3_0(IServiceProvider sp)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at OpenTelemetry.Extensions.Hosting.Implementation.TelemetryHostedService.Initialize(IServiceProvider serviceProvider)
   at OpenTelemetry.Extensions.Hosting.Implementation.TelemetryHostedService.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.Run(IHost host)
   at Program.<Main>$(String[] args)
```

## Reproduce

Create new cli app.
Configure open telemetry metrics grafana metrics.
run the following command.
```sh
dotnet publish -r win-x64 --self-contained true -p:PublishSingleFile=true
```
run the package.

**Comment by pyohannes** [comment]
Thanks @chinwobble for reporting this. We'll do a minor release fixing this bug this week.

**Comment by pyohannes** [comment]
@chinwobble We just release 0.6.0-beta.3 of the distribution with this bug fixed.
